'use strict';
/**
 * Translates the SQLite dialect used throughout LifegenTracker into PostgreSQL.
 * Only the constructs that actually appear in this code base are handled; the result is
 * cached per statement. Anything unexpected surfaces as a loud Postgres error (never silent).
 */

const cache = new Map();

/** Split SQL into [code, 'string literal', code, ...] so replacements never touch quoted text. */
function splitLiterals(sql) {
  const parts = [];
  let i = 0, start = 0;
  while (i < sql.length) {
    const ch = sql[i];
    if (ch === "'") {
      parts.push({ code: true, text: sql.slice(start, i) });
      let j = i + 1;
      while (j < sql.length) {
        if (sql[j] === "'") { if (sql[j + 1] === "'") { j += 2; continue; } break; }
        j++;
      }
      parts.push({ code: false, text: sql.slice(i, j + 1) });
      i = j + 1; start = i;
    } else if (ch === '-' && sql[i + 1] === '-') { // line comment
      const end = sql.indexOf('\n', i);
      const stop = end === -1 ? sql.length : end;
      parts.push({ code: true, text: sql.slice(start, i) });
      parts.push({ code: false, text: '' }); // drop the comment
      i = stop; start = i;
    } else i++;
  }
  parts.push({ code: true, text: sql.slice(start) });
  return parts;
}

const NOW_TS = "to_char((now() at time zone 'UTC'), 'YYYY-MM-DD HH24:MI:SS')";
const NOW_DATE = "to_char((now() at time zone 'UTC'), 'YYYY-MM-DD')";

/** Function calls that take quoted arguments — rewritten on the whole statement before literal splitting
 *  (the patterns are anchored on exact literals such as 'now', so they cannot match user data). */
function translateFunctions(s) {
  s = s.replace(/datetime\(\s*'now'\s*\)/gi, NOW_TS);
  s = s.replace(/date\(\s*'now'\s*,\s*'([+-]?\d+)\s+(day|days|month|months|year|years)'\s*\)/gi, (m, n, unit) => `to_char((now() at time zone 'UTC') ${n.startsWith('-') ? '-' : '+'} interval '${n.replace(/^[+-]/, '')} ${unit}', 'YYYY-MM-DD')`);
  s = s.replace(/date\(\s*'now'\s*\)/gi, NOW_DATE);
  s = s.replace(/strftime\(\s*'%Y-%m'\s*,\s*'now'\s*,\s*'localtime'\s*\)/gi, "to_char(now(), 'YYYY-MM')");
  s = s.replace(/strftime\(\s*'%Y-%m'\s*,\s*([\w.]+)\s*\)/gi, 'substr($1, 1, 7)');
  s = s.replace(/strftime\(\s*'%Y'\s*,\s*([\w.]+)\s*\)/gi, 'substr($1, 1, 4)');
  s = s.replace(/printf\(\s*'%0(\d)d'\s*,\s*([^)]+)\)/gi, (m, w, expr) => `to_char(${expr}, 'FM${'0'.repeat(Number(w))}')`);
  s = scalarMinMax(s);
  return s;
}

/** SQLite's 2-argument MIN(a, b) / MAX(a, b) are scalar functions → LEAST / GREATEST. */
function scalarMinMax(sql) {
  const re = /\b(MIN|MAX)\s*\(/gi;
  let m; let out = ''; let last = 0;
  while ((m = re.exec(sql))) {
    const open = m.index + m[0].length;
    let depth = 1, i = open, topComma = false, inStr = false;
    for (; i < sql.length && depth > 0; i++) {
      const c = sql[i];
      if (inStr) { if (c === "'") inStr = false; continue; }
      if (c === "'") inStr = true;
      else if (c === '(') depth++;
      else if (c === ')') depth--;
      else if (c === ',' && depth === 1) topComma = true;
    }
    if (topComma) {
      out += sql.slice(last, m.index) + (m[1].toUpperCase() === 'MIN' ? 'LEAST(' : 'GREATEST(');
      last = open;
    }
  }
  return out + sql.slice(last);
}

function translateCode(code, state) {
  let s = code;
  // --- schema ---
  s = s.replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  s = s.replace(/\s+COLLATE\s+NOCASE\b(?=\s*,|\s*\))/gi, ''); // column definitions: "UNIQUE COLLATE NOCASE,"
  s = s.replace(/(REFERENCES\s+\w+\s*\(\s*\w+\s*\)(?:\s+ON\s+DELETE\s+(?:CASCADE|SET\s+NULL|RESTRICT))?)/gi, '$1 DEFERRABLE INITIALLY IMMEDIATE');
  s = s.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, (m) => { state.orIgnore = true; return 'INSERT INTO'; });
  s = s.replace(/\bINSERT\s+OR\s+REPLACE\s+INTO\b/gi, () => { throw new Error('INSERT OR REPLACE is not supported on Postgres'); });
  // ORDER BY alias IS NULL, alias DESC  →  alias DESC NULLS LAST (Postgres cannot use an output alias inside an expression)
  s = s.replace(/\b([\w.]+)\s+IS\s+NULL\s*,\s*\1\s+DESC\b/gi, '$1 DESC NULLS LAST');
  s = s.replace(/\b([\w.]+)\s+IS\s+NULL\s*,\s*\1\s+ASC\b/gi, '$1 ASC NULLS LAST');
  // --- operators ---
  s = s.replace(/\bIS\s+NOT\s+\?/gi, 'IS DISTINCT FROM ?');
  s = s.replace(/\bIS\s+NOT\s+@(\w+)/gi, 'IS DISTINCT FROM @$1');
  s = s.replace(/\bLIKE\b/g, 'ILIKE'); // SQLite LIKE is case-insensitive
  s = s.replace(/([\w.]+)\s+COLLATE\s+NOCASE\b/gi, 'lower($1)'); // ORDER BY x COLLATE NOCASE
  return s;
}

/**
 * Translate one statement. Returns { text, params: ['name' | index, ...], orIgnore, kind, table }.
 * `params` describes how to build the positional array from the caller's arguments.
 */
function translate(sql) {
  const hit = cache.get(sql);
  if (hit) return hit;
  const state = { orIgnore: false };
  const parts = splitLiterals(translateFunctions(sql));
  const names = [];      // for @named params: order of first appearance
  let positional = 0;    // count of ?
  const out = parts.map((p) => {
    if (!p.code) return p.text;
    let t = translateCode(p.text, state);
    // bind parameters → $n
    t = t.replace(/\?|@([A-Za-z_]\w*)/g, (m, name) => {
      if (name) { let i = names.indexOf(name); if (i === -1) { names.push(name); i = names.length - 1; } return `$${i + 1}`; }
      positional += 1; return `$${positional}`;
    });
    return t;
  }).join('');
  if (names.length && positional) throw new Error('Mixed ? and @named parameters in one statement: ' + sql);
  let text = out;
  const m = /^\s*(INSERT|UPDATE|DELETE|SELECT|WITH|CREATE|ALTER|DROP|PRAGMA|BEGIN|COMMIT|ROLLBACK|SAVEPOINT|RELEASE|SET)\b/i.exec(text);
  const kind = m ? m[1].toUpperCase() : 'OTHER';
  let table = null;
  if (kind === 'INSERT') {
    const tm = /^\s*INSERT\s+INTO\s+(\w+)/i.exec(text);
    table = tm ? tm[1].toLowerCase() : null;
    if (state.orIgnore && !/ON\s+CONFLICT/i.test(text)) text = text.replace(/;?\s*$/, ' ON CONFLICT DO NOTHING');
  }
  const res = { text, names, positional, kind, table, orIgnore: state.orIgnore };
  cache.set(sql, res);
  return res;
}

/** Split a multi-statement script on top-level semicolons (ignores ; inside literals). */
function splitStatements(sql) {
  const out = [];
  let buf = '';
  for (const p of splitLiterals(sql)) {
    if (!p.code) { buf += p.text; continue; }
    const pieces = p.text.split(';');
    for (let i = 0; i < pieces.length; i++) {
      buf += pieces[i];
      if (i < pieces.length - 1) { out.push(buf); buf = ''; }
    }
  }
  if (buf.trim()) out.push(buf);
  return out.filter((x) => x.trim());
}

/** Translate a whole script (DDL / migrations) statement by statement. */
function translateScript(sql) {
  return splitStatements(sql).map((st) => translate(st).text).join(';\n') + ';';
}

module.exports = { translate, translateScript, splitStatements, splitLiterals };
